import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ecommerce_app_login/constants/assets.dart';

void main() {
  test('assets assets test', () {
    expect(File(Assets.congrats).existsSync(), isTrue);
    expect(File(Assets.emptyAppointments).existsSync(), isTrue);
    expect(File(Assets.emptyCategories).existsSync(), isTrue);
    expect(File(Assets.emptyContact).existsSync(), isTrue);
    expect(File(Assets.emptyEvent).existsSync(), isTrue);
    expect(File(Assets.emptyMyLeads).existsSync(), isTrue);
    expect(File(Assets.emptyMyNetwork).existsSync(), isTrue);
    expect(File(Assets.emptyMyPayment).existsSync(), isTrue);
    expect(File(Assets.emptyNetworkRequest).existsSync(), isTrue);
    expect(File(Assets.emptyPastEvents).existsSync(), isTrue);
    expect(File(Assets.emptyUpcomingEvents).existsSync(), isTrue);
    expect(File(Assets.mailFailed).existsSync(), isTrue);
    expect(File(Assets.mainSuccess).existsSync(), isTrue);
    expect(File(Assets.noResultsFound).existsSync(), isTrue);
    expect(File(Assets.offline).existsSync(), isTrue);
    expect(File(Assets.placeholder).existsSync(), isTrue);
    expect(File(Assets.referral1).existsSync(), isTrue);
    expect(File(Assets.referral2).existsSync(), isTrue);
    expect(File(Assets.titleDecoration).existsSync(), isTrue);
    expect(File(Assets.titleUnderline).existsSync(), isTrue);
    expect(File(Assets.addCategory).existsSync(), isTrue);
    expect(File(Assets.addLead).existsSync(), isTrue);
    expect(File(Assets.addNetwork).existsSync(), isTrue);
    expect(File(Assets.arrowRight).existsSync(), isTrue);
    expect(File(Assets.back).existsSync(), isTrue);
    expect(File(Assets.bookmarkCheck).existsSync(), isTrue);
    expect(File(Assets.bookmark).existsSync(), isTrue);
    expect(File(Assets.calendarPlus1).existsSync(), isTrue);
    expect(File(Assets.calendar).existsSync(), isTrue);
    expect(File(Assets.calls).existsSync(), isTrue);
    expect(File(Assets.clock).existsSync(), isTrue);
    expect(File(Assets.createContact).existsSync(), isTrue);
    expect(File(Assets.defaultUserProfile).existsSync(), isTrue);
    expect(File(Assets.download).existsSync(), isTrue);
    expect(File(Assets.editAvatar).existsSync(), isTrue);
    expect(File(Assets.eyeClosed).existsSync(), isTrue);
    expect(File(Assets.eyeOpen).existsSync(), isTrue);
    expect(File(Assets.facebook).existsSync(), isTrue);
    expect(File(Assets.github).existsSync(), isTrue);
    expect(File(Assets.home).existsSync(), isTrue);
    expect(File(Assets.instagram).existsSync(), isTrue);
    expect(File(Assets.linkedin).existsSync(), isTrue);
    expect(File(Assets.mail).existsSync(), isTrue);
    expect(File(Assets.mapPin).existsSync(), isTrue);
    expect(File(Assets.membership).existsSync(), isTrue);
    expect(File(Assets.messageIcon).existsSync(), isTrue);
    expect(File(Assets.passwordLock).existsSync(), isTrue);
    expect(File(Assets.peopleRoof).existsSync(), isTrue);
    expect(File(Assets.profileIcon).existsSync(), isTrue);
    expect(File(Assets.share).existsSync(), isTrue);
    expect(File(Assets.sheduleAppointment).existsSync(), isTrue);
    expect(File(Assets.users).existsSync(), isTrue);
    expect(File(Assets.web).existsSync(), isTrue);
    expect(File(Assets.whatsapp).existsSync(), isTrue);
  });
}
